---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit the README.Rmd file -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab report #1

Follow the instructions posted at https://ds202-at-isu.github.io/labs.html for the lab assignment. The work is meant to be finished during the lab time, but you have time until Monday evening to polish things.

Include your answers in this document (Rmd file). Make sure that it knits properly (into the md file). Upload both the Rmd and the md file to your repository.  

All submissions to the github repo will be automatically uploaded for grading once the due date is passed.
Submit a link to your repository on Canvas (only one submission per team) to signal to the instructors that you are done with your submission.

# Step 1

# Step 2

Yes, there is a variable of special interest. \
This main variable is called: **"Sales Price"**.\

# Step 3

# Step 4

## Grace's  Year Built and sale price

plot(ames$YearBuilt,
     ames$`Sale Price`,
     main = "Sale Price vs Year Built",
     xlab = "Year Built",
     ylab = "Sale Price",
     xlim = c(1850, 2025),
     ylim = c(0, 800000),
     pch = 16)
# I can see from this scatterplot that all  of the homes were bulit after 1850 and as time goes on, the price of houses increases which makes sense. 

## Kyle's Work

## Owen's Work

## Shiva's Work

## Olivia's Work
